"""empty message

Revision ID: 99dc7ef4b73f
Revises: 1c87cb657a87
Create Date: 2019-06-12 12:14:56.742144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99dc7ef4b73f'
down_revision = '1c87cb657a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'user_role_ibfk_2', 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key(u'user_role_ibfk_2', 'user_role', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
