"""empty message

Revision ID: 9ac2032d8e36
Revises: fd10f65ec17f
Create Date: 2019-05-25 19:30:51.841778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac2032d8e36'
down_revision = 'fd10f65ec17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('createat', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['createdby'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
