"""empty message

Revision ID: b1e051ec0a94
Revises: c76c5c320902
Create Date: 2019-05-26 16:03:49.936972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e051ec0a94'
down_revision = 'c76c5c320902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('createdat', sa.DateTime(), nullable=True))
    op.drop_column('article', 'createat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('createat', sa.DATETIME(), nullable=True))
    op.drop_column('article', 'createdat')
    # ### end Alembic commands ###
