"""unique role name

Revision ID: b80387316205
Revises: 03b1bade3502
Create Date: 2019-04-25 08:46:53.324586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80387316205'
down_revision = '03b1bade3502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_name'), table_name='role')
    # ### end Alembic commands ###
